name: Go format
on: [push]

jobs:
  gofmt:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: false
      - name: gofmt
        run: |
          gofmt -s -w ./
